version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: docker build -t ${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1} .
          name: build

workflows:
  main:
    jobs:
      - build
